CREATE TABLE schedule(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
    name VARCHAR(100) NOT NULL COMMENT '작성자 명',
    todo TEXT COMMENT '할일',
    password VARCHAR(100) NOT NULL COMMENT '비밀번호',
    created_at TIMESTAMP NOT NULL COMMENT  '생성일',
    updated_at TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);